# Generated by Django 2.2.28 on 2022-08-25 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_auto_20220824_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_master', to=settings.AUTH_USER_MODEL),
        ),
    ]
