# Generated by Django 4.0.5 on 2022-08-08 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='image',
            new_name='images',
        ),
    ]
