# Generated by Django 4.0.5 on 2022-08-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_rename_image_messages_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='mediachat/'),
        ),
    ]
